/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.3/samples
 */
plugins {
    java
    application
}

repositories {
    maven { setUrl("https://www.jitpack.io") }
    mavenCentral()
}

dependencies {
    implementation("com.github.cylixlee:sample-java-lib:1.0")
}

application {
    mainClass = "io.github.cylixlee.sample.Usage"
}